version: '3.4'

services:
  scimaterials.ui.mvc:
    container_name: mvc
    image: scimaterialsuimvc:latest
    build:
      context: .
      dockerfile: UI/SciMaterials.UI.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5185:80"
  
  postgres_db:
    container_name: postgres
    image: postgres:latest
    build:
      context: .
      
