name: SciMaterialsTest

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies...
      run: dotnet restore SciMaterialsFork/SciMaterialsActions.yml
    - name: Build Project...
      run: dotnet build --no-restore SciMaterialsFork/SciMaterialsActions.yml
    - name: Test Project...
      run: dotnet test --no-build SciMaterialsFork/SciMaterialsActions.yml
